export const jobs = [
  {
    id: "job-1048",
    jobNumber: "J-1048",
    customer: "Northstar Hydraulics",
    product: "Valve body assembly",
    status: "closed",
    dueDate: "2026-09-12",
    openedAt: "2026-08-18",
    customerId: "cust-northstar",
    revenue: 68400,
    estimatedCost: 49200,
    actualCost: 57780,
    margin: 10620,
    marginRate: 15.5,
    primaryLeak: "Material price variance",
    confidence: "high",
    costLines: [
      {
        category: "Material",
        estimated: 24400,
        actual: 30850,
        variance: 6450,
        source: "ERP purchase receipts",
        note: "Steel and valve inserts landed above quote assumptions.",
      },
      {
        category: "Direct labor",
        estimated: 12800,
        actual: 14240,
        variance: 1440,
        source: "Shop-floor time entries",
        note: "Finishing operation used 18 hours more than routed.",
      },
      {
        category: "Outside processing",
        estimated: 6200,
        actual: 6890,
        variance: 690,
        source: "QuickBooks vendor bills",
        note: "Expedite charge added by heat-treatment supplier.",
      },
      {
        category: "Applied overhead",
        estimated: 5800,
        actual: 5800,
        variance: 0,
        source: "Costing policy",
        note: "Applied using the approved machine-hour rate.",
      },
    ],
  },
  {
    id: "job-1051",
    jobNumber: "J-1051",
    customer: "Apex Motion",
    product: "Precision actuator bracket",
    status: "closed",
    dueDate: "2026-09-14",
    openedAt: "2026-08-22",
    customerId: "cust-apex",
    revenue: 42600,
    estimatedCost: 30300,
    actualCost: 44820,
    margin: -2220,
    marginRate: -5.2,
    primaryLeak: "Rework and labor overrun",
    confidence: "high",
    costLines: [
      {
        category: "Material",
        estimated: 12200,
        actual: 13400,
        variance: 1200,
        source: "ERP material issues",
        note: "One replacement plate issued after a failed inspection.",
      },
      {
        category: "Direct labor",
        estimated: 9400,
        actual: 17560,
        variance: 8160,
        source: "Shop-floor time entries",
        note: "Two machining operations were repeated after tolerance failure.",
      },
      {
        category: "Outside processing",
        estimated: 4700,
        actual: 7060,
        variance: 2360,
        source: "QuickBooks vendor bills",
        note: "Second anodizing cycle and rush freight were unquoted.",
      },
      {
        category: "Applied overhead",
        estimated: 4000,
        actual: 6800,
        variance: 2800,
        source: "Costing policy",
        note: "Additional machine and inspection hours increased overhead.",
      },
    ],
  },
  {
    id: "job-1054",
    jobNumber: "J-1054",
    customer: "Beacon Food Systems",
    product: "Sanitary conveyor frame",
    status: "closed",
    dueDate: "2026-09-15",
    openedAt: "2026-08-25",
    customerId: "cust-beacon",
    revenue: 91800,
    estimatedCost: 65900,
    actualCost: 70120,
    margin: 21680,
    marginRate: 23.6,
    primaryLeak: "Welding labor variance",
    confidence: "high",
    costLines: [
      {
        category: "Material",
        estimated: 35800,
        actual: 36140,
        variance: 340,
        source: "ERP material issues",
        note: "Material usage remained close to estimate.",
      },
      {
        category: "Direct labor",
        estimated: 18100,
        actual: 21480,
        variance: 3380,
        source: "Shop-floor time entries",
        note: "Polishing and sanitary weld cleanup took longer than routed.",
      },
      {
        category: "Outside processing",
        estimated: 5400,
        actual: 5900,
        variance: 500,
        source: "QuickBooks vendor bills",
        note: "Passivation charge increased slightly.",
      },
      {
        category: "Applied overhead",
        estimated: 6600,
        actual: 6600,
        variance: 0,
        source: "Costing policy",
        note: "Applied using approved labor-hour rates.",
      },
    ],
  },
  {
    id: "job-1057",
    jobNumber: "J-1057",
    customer: "Orion Packaging",
    product: "Cartoner change-part kit",
    status: "at-risk",
    dueDate: "2026-09-24",
    openedAt: "2026-09-01",
    customerId: "cust-orion",
    revenue: 55200,
    estimatedCost: 37600,
    actualCost: 42100,
    margin: 13100,
    marginRate: 23.7,
    primaryLeak: "Open labor overrun",
    confidence: "medium",
    costLines: [
      {
        category: "Material",
        estimated: 16400,
        actual: 16950,
        variance: 550,
        source: "ERP material issues",
        note: "Nearly complete; one purchase receipt remains open.",
      },
      {
        category: "Direct labor",
        estimated: 12600,
        actual: 16600,
        variance: 4000,
        source: "Shop-floor time entries",
        note: "Assembly has consumed 132% of routed hours.",
      },
      {
        category: "Outside processing",
        estimated: 3500,
        actual: 3440,
        variance: -60,
        source: "QuickBooks vendor bills",
        note: "Current bills are within estimate.",
      },
      {
        category: "Applied overhead",
        estimated: 5100,
        actual: 5110,
        variance: 10,
        source: "Costing policy",
        note: "Projected at current labor completion.",
      },
    ],
  },
  {
    id: "job-1060",
    jobNumber: "J-1060",
    customer: "Helios Robotics",
    product: "Robot base weldment",
    status: "open",
    dueDate: "2026-09-29",
    openedAt: "2026-09-05",
    customerId: "cust-helios",
    revenue: 76200,
    estimatedCost: 50800,
    actualCost: 29850,
    margin: 46350,
    marginRate: 60.8,
    primaryLeak: "No current exception",
    confidence: "medium",
    costLines: [
      {
        category: "Material",
        estimated: 28400,
        actual: 25200,
        variance: -3200,
        source: "ERP material issues",
        note: "Most material has been issued.",
      },
      {
        category: "Direct labor",
        estimated: 12400,
        actual: 4650,
        variance: -7750,
        source: "Shop-floor time entries",
        note: "Job is 41% complete; margin is not final.",
      },
      {
        category: "Outside processing",
        estimated: 4800,
        actual: 0,
        variance: -4800,
        source: "QuickBooks vendor bills",
        note: "Powder coating has not yet been invoiced.",
      },
      {
        category: "Applied overhead",
        estimated: 5200,
        actual: 0,
        variance: -5200,
        source: "Costing policy",
        note: "Overhead will apply as production advances.",
      },
    ],
  },
  {
    id: "job-1044",
    jobNumber: "J-1044",
    customer: "Summit AgTech",
    product: "Seeder manifold",
    status: "closed",
    dueDate: "2026-09-08",
    openedAt: "2026-08-11",
    customerId: "cust-summit",
    revenue: 34700,
    estimatedCost: 23600,
    actualCost: 25140,
    margin: 9560,
    marginRate: 27.6,
    primaryLeak: "Minor material variance",
    confidence: "high",
    costLines: [
      {
        category: "Material",
        estimated: 11300,
        actual: 12420,
        variance: 1120,
        source: "ERP material issues",
        note: "Brass fitting price increased after quote.",
      },
      {
        category: "Direct labor",
        estimated: 7500,
        actual: 7800,
        variance: 300,
        source: "Shop-floor time entries",
        note: "Labor remained close to route.",
      },
      {
        category: "Outside processing",
        estimated: 1900,
        actual: 2020,
        variance: 120,
        source: "QuickBooks vendor bills",
        note: "Plating charge increased slightly.",
      },
      {
        category: "Applied overhead",
        estimated: 2900,
        actual: 2900,
        variance: 0,
        source: "Costing policy",
        note: "Applied using approved labor-hour rates.",
      },
    ],
  },
  {
    id: "job-1046",
    jobNumber: "J-1046",
    customer: "Vector Climate",
    product: "Industrial fan housing",
    status: "closed",
    dueDate: "2026-09-10",
    openedAt: "2026-08-14",
    customerId: "cust-vector",
    revenue: 50600,
    estimatedCost: 35100,
    actualCost: 43740,
    margin: 6860,
    marginRate: 13.6,
    primaryLeak: "Scrap and replacement material",
    confidence: "high",
    costLines: [
      {
        category: "Material",
        estimated: 17800,
        actual: 23100,
        variance: 5300,
        source: "ERP material issues",
        note: "Replacement sheet issued after forming scrap.",
      },
      {
        category: "Direct labor",
        estimated: 9700,
        actual: 11840,
        variance: 2140,
        source: "Shop-floor time entries",
        note: "Forming and weld repair exceeded route.",
      },
      {
        category: "Outside processing",
        estimated: 3100,
        actual: 3300,
        variance: 200,
        source: "QuickBooks vendor bills",
        note: "Powder coating remained near estimate.",
      },
      {
        category: "Applied overhead",
        estimated: 4500,
        actual: 5500,
        variance: 1000,
        source: "Costing policy",
        note: "Additional direct hours increased applied overhead.",
      },
    ],
  },
] as const;

export const withEvidence = (job: (typeof jobs)[number]) => ({
  ...job,
  evidence: [
    {
      label: "Revenue",
      value: `$${job.revenue.toLocaleString("en-US")}`,
      source: "QuickBooks invoices",
      detail: `Matched to ${job.jobNumber} using the customer PO and job number.`,
    },
    {
      label: "Actual cost",
      value: `$${job.actualCost.toLocaleString("en-US")}`,
      source: "ERP + shop-floor time + vendor bills",
      detail: "Material, labor, outside processing, and applied overhead reconciled.",
    },
    {
      label: "Contribution margin",
      value: `${job.marginRate.toFixed(1)}%`,
      source: "Approved costing definition",
      detail: "Revenue less actual material, direct labor, outside processing, and applied overhead.",
    },
  ],
});

export const sources = [
  {
    id: "src-quickbooks",
    name: "QuickBooks Online",
    type: "Accounting",
    status: "connected",
    recordCount: 1284,
    lastSyncedAt: "2026-09-19T08:42:00.000Z",
    detail: "Invoices, vendor bills, customers, and payments are reconciled.",
  },
  {
    id: "src-erp",
    name: "Shop ERP export",
    type: "ERP",
    status: "connected",
    recordCount: 5842,
    lastSyncedAt: "2026-09-19T08:39:00.000Z",
    detail: "Jobs, estimates, material issues, routings, and completion status.",
  },
  {
    id: "src-labor",
    name: "Labor tracking.xlsx",
    type: "Spreadsheet",
    status: "needs-review",
    recordCount: 916,
    lastSyncedAt: "2026-09-19T07:55:00.000Z",
    detail: "Three employee aliases need confirmation; affected rows are excluded.",
  },
] as const;